/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.osullivan.minesweeper;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.PrintStream;

public class App {
  private Player player;

  public App(Player player){
    this.player = player;
  }

  public void playGame() throws IOException{
    while(this.player.isPlaying()){
      this.player.makeOneMove();
    }
  }

  public static void main(String[] args) throws IOException {
    Board board = new Board(10, 10, 10);
    BufferedReader inStream = new BufferedReader(new InputStreamReader(System.in));
    PrintStream outStream = System.out;

    Player player = new TextPlayer(board, outStream, inStream);
    App app = new App(player);
    app.playGame();
  }
}
